# Generated by Django 3.1.6 on 2021-04-03 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ngo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventmanager',
            name='organisation_picture',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='organisation_pics'),
        ),
    ]
