# Generated by Django 3.1.6 on 2021-04-03 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ngo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=100)),
                ('event_manager', models.CharField(max_length=100)),
                ('event_contact', models.CharField(max_length=13)),
                ('event_address', models.CharField(max_length=200)),
                ('event_location', models.CharField(max_length=100)),
                ('event_city', models.CharField(max_length=100)),
                ('event_state', models.CharField(max_length=100)),
                ('event_zipcode', models.CharField(max_length=10)),
                ('event_organiser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ngo.eventmanager')),
            ],
        ),
    ]
