# Generated by Django 3.1.6 on 2021-04-03 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventManager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='postevent',
            name='event_foodqty',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
