# Generated by Django 3.1.6 on 2021-04-04 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventManager', '0003_auto_20210403_1956'),
    ]

    operations = [
        migrations.AddField(
            model_name='postevent',
            name='event_lat',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='postevent',
            name='event_lon',
            field=models.CharField(default='', max_length=100),
        ),
    ]
